export const dummy_data = [
  {
    id: 1,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 2,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Review",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 3,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Confirm",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 4,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 5,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 6,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 7,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 8,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 9,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 10,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 11,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 12,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 13,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 14,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 15,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 16,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 17,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 18,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 19,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 20,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
  {
    id: 21,
    assignedTo: "john doe",
    question: "User Interface",
    askedBy: "jane doe",
    reporter: "mccorn@nationwide.com",
    status: "Answer",
    date: "Mon Sept 27 2020 16:00:00",
  },
];
