export const cards_dum_data = [
  {
    id: 1,
    isChecked: true,
    title:
      "Lorems upsum dolor sit amet, consect tuernsectdf adipisc dolor sit amet, consect? dolor sit amet dolor sit amet",
    description: `Acceptance criteria is formed using the business logic created during the product design process. Engineering, QA and UX will take the agreed product logic and ensure blah blah blah (should be cut off at ens)`,
    avatarUrl: `https://thiscatdoesnotexist.com">`,
    altText: `alternate text`,
    salutation: `adventurer`,
    views: 1000,
    dateTimeStamp: "Mon Sept 27 2020 16:00:00",
    userName: `JDM Baggins`,
    hasConflict: true,
  },
  {
    id: 2,
    isChecked: false,
    title:
      "2nd Lorem upsum dolor sit amet, consect tuernsectdf adipisc dolor sit amet, consect? dolor sit amet dolor sit amet",
    description: `2 Acceptance criteria is formed using the business logic created during the product design process. Engineering, QA and UX will take the agreed product logic and ensure blah blah blah (should be cut off at ens)`,
    avatarUrl: `https://thiscatdoesnotexist.com">`,
    altText: `alternate text`,
    userName: `Bilbo Baggins`,
    salutation: `adventurer`,
    views: 500,
    dateTimeStamp: "Mon Sept 28 2020 15:00:00",
    hasConflict: false,
  },
  {
    id: 3,
    isChecked: false,
    title:
      "3rd Lorem upsum dolor sit amet, consect tuernsectdf adipisc dolor sit amet, consect? dolor sit amet dolor sit amet",
    description: `3 Acceptance criteria is formed using the business logic created during the product design process. Engineering, QA and UX will take the agreed product logic and ensure blah blah blah (should be cut off at ens)`,
    avatarUrl: `https://thiscatdoesnotexist.com">`,
    altText: `alternate text`,
    salutation: `adventurer`,
    views: 3000,
    dateTimeStamp: "Mon Sept 26 2020 13:00:00",
    userName: `KENNETH Baggins`,
    hasConflict: true,
  },
  {
    id: 4,
    isChecked: false,
    title:
      "4th Lorem upsum dolor sit amet, consect tuernsectdf adipisc dolor sit amet, consect? dolor sit amet dolor sit amet",
    description: `Acceptance criteria is formed using the business logic created during the product design process. Engineering, QA and UX will take the agreed product logic and ensure blah blah blah (should be cut off at ens)`,
    avatarUrl: `https://thiscatdoesnotexist.com">`,
    altText: `alternate text`,
    salutation: `adventurer`,
    views: 4000,
    dateTimeStamp: "Mon Sept 28 2020 12:00:00",
    userName: `JEFF Baggins`,
    hasConflict: false,
  },
  {
    id: 5,
    isChecked: false,
    title:
      "5 Lorem upsum dolor sit amet, consect tuernsectdf adipisc dolor sit amet, consect? dolor sit amet dolor sit amet",
    description: `Acceptance criteria is formed using the business logic created during the product design process. Engineering, QA and UX will take the agreed product logic and ensure blah blah blah (should be cut off at ens)`,
    avatarUrl: `https://thiscatdoesnotexist.com">`,
    altText: `alternate text`,
    salutation: `adventurer`,
    views: 5000,
    dateTimeStamp: "Mon Sept 28 2020 11:00:00",
    userName: `RAM Baggins`,
    hasConflict: false,
  },
  {
    id: 6,
    isChecked: false,
    title:
      "6 Lorem upsum dolor sit amet, consect tuernsectdf adipisc dolor sit amet, consect? dolor sit amet dolor sit amet",
    description: `Acceptance criteria is formed using the business logic created during the product design process. Engineering, QA and UX will take the agreed product logic and ensure blah blah blah (should be cut off at ens)`,
    avatarUrl: `https://thiscatdoesnotexist.com">`,
    altText: `alternate text`,
    userName: `Bilbo Baggins`,
    salutation: `adventurer`,
    views: 6000,
    dateTimeStamp: "Mon Sept 28 2020 10:00:00",
    hasConflict: false,
  },
  {
    id: 7,
    isChecked: false,
    title:
      "7 Lorem upsum dolor sit amet, consect tuernsectdf adipisc dolor sit amet, consect? dolor sit amet dolor sit amet",
    description: `Acceptance criteria is formed using the business logic created during the product design process. Engineering, QA and UX will take the agreed product logic and ensure blah blah blah (should be cut off at ens)`,
    avatarUrl: `https://thiscatdoesnotexist.com">`,
    altText: `alternate text`,
    userName: `Bilbo Baggins`,
    salutation: `adventurer`,
    views: 7000,
    dateTimeStamp: "Mon Sept 28 2020 09:00:00",
    hasConflict: false,
  },
  {
    id: 8,
    isChecked: false,
    title:
      "8 Lorem upsum dolor sit amet, consect tuernsectdf adipisc dolor sit amet, consect? dolor sit amet dolor sit amet",
    description: `Acceptance criteria is formed using the business logic created during the product design process. Engineering, QA and UX will take the agreed product logic and ensure blah blah blah (should be cut off at ens)`,
    avatarUrl: `https://thiscatdoesnotexist.com">`,
    altText: `alternate text`,
    userName: `Bilbo Baggins`,
    salutation: `adventurer`,
    views: 8000,
    dateTimeStamp: "Mon Sept 28 2020 08:00:00",
    hasConflict: false,
  },
  {
    id: 9,
    isChecked: false,
    title:
      "9 Lorem upsum dolor sit amet, consect tuernsectdf adipisc dolor sit amet, consect? dolor sit amet dolor sit amet",
    description: `Acceptance criteria is formed using the business logic created during the product design process. Engineering, QA and UX will take the agreed product logic and ensure blah blah blah (should be cut off at ens)`,
    avatarUrl: `https://thiscatdoesnotexist.com">`,
    altText: `alternate text`,
    userName: `Bilbo Baggins`,
    salutation: `adventurer`,
    views: 9000,
    dateTimeStamp: "Mon Sept 28 2020 07:00:00",
    hasConflict: false,
  },
  {
    id: 10,
    isChecked: false,
    title:
      "10 Lorem upsum dolor sit amet, consect tuernsectdf adipisc dolor sit amet, consect? dolor sit amet dolor sit amet",
    description: `Acceptance criteria is formed using the business logic created during the product design process. Engineering, QA and UX will take the agreed product logic and ensure blah blah blah (should be cut off at ens)`,
    avatarUrl: `https://thiscatdoesnotexist.com">`,
    altText: `alternate text`,
    userName: `Bilbo Baggins`,
    salutation: `adventurer`,
    views: 10000,
    dateTimeStamp: "Mon Sept 28 2020 06:00:00",
    hasConflict: false,
  },
];
