export const dummy_data = [
  {
    id: 1,
    created: "23 days ago",
    createdBy: "Username",
    question:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    requestStats: "Open Request",
    assignee: "Review",
  },
  {
    id: 1,
    created: "23 days ago",
    createdBy: "Username",
    question: "Lorem ipsum",
    requestStats: "Open Review",
    assignee: "Accurate",
  },
  {
    id: 1,
    created: "23 days ago",
    createdBy: "Username",
    question: "Lorem ipsum",
    requestStats: "Open Request",
    assignee: "Answer",
  },
  {
    id: 1,
    created: "23 days ago",
    createdBy: "Username",
    question: "Lorem ipsum",
    requestStats: "Open Review",
    assignee: "Answer",
  },
  {
    id: 1,
    created: "23 days ago",
    createdBy: "Username",
    question: "Lorem ipsum",
    requestStats: "Open Request",
    assignee: "Answer",
  },
  {
    id: 1,
    created: "23 days ago",
    createdBy: "Username",
    question: "Lorem ipsum",
    requestStats: "Open Request",
    assignee: "Answer",
  },
  {
    id: 1,
    created: "23 days ago",
    createdBy: "Username",
    question: "Lorem ipsum",
    requestStats: "Open Request",
    assignee: "Answer",
  },
  {
    id: 1,
    created: "23 days ago",
    createdBy: "Username",
    question: "Lorem ipsum",
    requestStats: "Open Request",
    assignee: "Answer",
  },
  {
    id: 1,
    created: "23 days ago",
    createdBy: "Username",
    question: "Lorem ipsum",
    requestStats: "Open Request",
    assignee: "Answer",
  },
  {
    id: 1,
    created: "23 days ago",
    createdBy: "Username",
    question: "Lorem ipsum",
    requestStats: "Open Request",
    assignee: "Answer",
  },
  {
    id: 1,
    created: "23 days ago",
    createdBy: "Username",
    question: "Lorem ipsum",
    requestStats: "Open Request",
    assignee: "Answer",
  },
  {
    id: 1,
    created: "23 days ago",
    createdBy: "Username",
    question: "Lorem ipsum",
    requestStats: "Open Request",
    assignee: "Answer",
  },
  {
    id: 1,
    created: "23 days ago",
    createdBy: "Username",
    question: "Lorem ipsum",
    requestStats: "Open Request",
    assignee: "Answer",
  },
];
