export const dummy_data = [
  {
    content: `
    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tempus sit amet lorem ut malesuada. Maecenas tellus ex, pharetra non purus a, sagittis facilisis nibh. Morbi sit amet justo sapien. Praesent luctus malesuada ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent enim nunc, maximus eget ornare sit amet, faucibus in purus. Donec et sem sit amet ex sodales auctor. Pellentesque fringilla fermentum dui et aliquam. Integer imperdiet sem vel nunc aliquam, eu interdum neque pellentesque. Proin gravida, erat sed ultricies vulputate, dui massa viverra lacus, eu consequat risus ligula quis felis. Duis malesuada convallis lectus sit amet porttitor. Duis viverra, eros et vestibulum sagittis, diam ex finibus tellus, in laoreet diam erat dignissim sem. Aenean lobortis mi eu elit pretium dapibus. Cras iaculis augue nunc, varius viverra eros eleifend vitae.
     Maecenas pretium ac est quis aliquet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc consectetur et libero sit amet facilisis. Curabitur vel ultrices velit, vel consequat quam. Fusce cursus varius mi sit amet tincidunt. Praesent nisi erat, consectetur consequat sagittis et, rhoncus faucibus nulla. Cras ornare, mauris quis ornare aliquet, massa felis egestas sapien, quis rutrum elit dui sed ligula. Nam ipsum nibh, faucibus sit amet orci commodo, aliquet ultricies tortor. Cras iaculis purus non ante egestas tempus. Duis a cursus nisl.
     </p><br>
     <p>
     Sed a posuere libero. Fusce dui augue, laoreet sed lorem vel, luctus convallis nisl. Duis rhoncus lectus viverra, sagittis sapien nec, pulvinar justo. Proin auctor lorem quis scelerisque finibus. Nam maximus iaculis metus sed eleifend. Sed euismod euismod rutrum. Duis ut luctus tellus, sit amet bibendum enim. Aenean et lectus quis diam sagittis accumsan. In hac habitasse platea dictumst. Donec lacus velit, aliquet eu ex vitae, porta commodo justo. Nunc at blandit odio.
  </p>
  <br>
     Duis auctor ipsum nec nulla egestas, sed volutpat arcu congue. Fusce arcu leo, pulvinar ut ipsum sed, congue auctor felis. Aliquam tellus augue, fermentum eu diam at, dapibus sagittis orci. Maecenas suscipit, risus id consectetur luctus, nisi dolor dictum orci, vel venenatis nunc nisl vel tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam fringilla eleifend est nec tempor. Proin eget enim massa. Etiam accumsan nunc convallis libero ullamcorper, a ornare purus molestie. Nullam varius nisi eu orci malesuada dictum non ut felis. Etiam pretium nulla non sapien venenatis, vel interdum augue commodo. Phasellus eu efficitur ligula. Phasellus congue libero sit amet ipsum hendrerit elementum.
   Nullam eu tellus augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ut tempus sapien. Vivamus gravida imperdiet ultricies. Curabitur eget euismod dui. Praesent lectus massa, commodo non dolor quis, bibendum interdum tellus. Mauris commodo mauris ligula, eu pharetra libero semper eget. Sed tincidunt odio eget neque efficitur, eget pretium leo aliquet. Nulla et viverra tellus. Cras sodales sed purus lobortis bibendum. Curabitur mollis porta odio, et volutpat nunc semper sit amet. Nam fermentum sed orci id eleifend. Ut vitae magna bibendum, porta urna quis, sagittis dui.
     `,
  },
];
