export const dum_data = [
  {
    id: 1,
    topic: "Topic Name",
    subTopic: [
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
    ],
  },
  {
    id: 2,
    topic: "Topic Name",
    subTopic: [
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
    ],
  },
  {
    id: 3,
    topic: "Topic Name",
    subTopic: [
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
    ],
  },
  {
    id: 4,
    topic: "Topic Name",
    subTopic: [
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
    ],
  },
  {
    id: 5,
    topic: "Topic Name",
    subTopic: [
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
    ],
  },
  {
    id: 6,
    topic: "Topic Name",
    subTopic: [
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
    ],
  },
  {
    id: 7,
    topic: "Topic Name",
    subTopic: [
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
    ],
  },
  {
    id: 8,
    topic: "Topic Name",
    subTopic: [
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
    ],
  },
  {
    id: 9,
    topic: "Topic Name",
    subTopic: [
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
    ],
  },
  {
    id: 10,
    topic: "Topic Name",
    subTopic: [
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
      { name: "Sub-topic" },
    ],
  },
];
