export const dummy_data = [
  {
    id: 1,
    t: true,
    p: true,
    components: "User Interface",
    key: "FAS-74",
    summary: "Add ability to show status of request",
    reporter: "mccorn@nationwide.com",
    assignedTo: "john doe",
  },
  {
    id: 2,
    t: false,
    p: false,
    components: "User Interface",
    key: "FAS-74",
    summary: "Add ability to show status of request",
    reporter: "mccorn@nationwide.com",
    assignedTo: "john doe",
  },
  {
    id: 3,
    t: true,
    p: false,
    components: "User Interface",
    key: "FAS-74",
    summary: "Add ability to show status of request",
    reporter: "mccorn@nationwide.com",
    assignedTo: "john doe",
  },
  {
    id: 4,
    t: true,
    p: false,
    components: "User Interface",
    key: "FAS-74",
    summary: "Add ability to show status of request",
    reporter: "mccorn@nationwide.com",
    assignedTo: "john doe",
  },
];
